server.port=8082
#spring.profiles.active=test

spring.application.name=image-service
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

################# AWS S3
aws.s3.bucket-name=storage-yalantis
aws.s3.bucket-url=https://storage-yalantis.s3.eu-west-3.amazonaws.com/

#image-service.server.baseurl=https://localhost:9981
image-service.server.baseurl=https://ec2-51-21-199-63.eu-west-3.compute.amazonaws.com

################# AWS SNS properties
cloud.aws.region.static=${AWS_REGION}
cloud.aws.region.auto=false
cloud.aws.stack.auto = false
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}
cloud.aws.topic.arn=arn:aws:sns:eu-west-3:233047280808:upload-image
cloud.aws.topic.name=upload-image

security.basic.enabled=false

mongodb://yalantis:Test_Pass2022@yalantis.cluster-c54k44a8kqas.eu-west-3.docdb.amazonaws.com:27017/?tls=true&tlsCAFile=global-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false

################# Mongodb
spring.data.mongodb.uri=mongodb://localhost:27018/aws_project

################# Multipart file
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

################# Keycloak
spring.security.oauth2.client.registration.keycloak.client-id=login-app
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid

# the base URI for the authorization server
spring.security.oauth2.client.provider.keycloak.issuer-uri=https://ec2-35-180-66-169.eu-west-3.compute.amazonaws.com:8443/realms/SpringBootKeycloak
#spring.security.oauth2.client.provider.keycloak.issuer-uri=https://localhost:8443/realms/SpringBootKeycloak

# to populate our controller?s Principal with a proper user
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username

# to validate JWT token using Keycloak server
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://ec2-35-180-66-169.eu-west-3.compute.amazonaws.com:8443/realms/SpringBootKeycloak
#spring.security.oauth2.resourceserver.jwt.issuer-uri=https://localhost:8443/realms/SpringBootKeycloak







